### ISSUE TITLE
not working with some type of m3u

### ISSUE THREAD

**Issue by sunsgs** [jaruba/wcjs-player#56]
i am trying to load this m3u file, with no success
 player.addPlaylist("http://siptv.eu/lists/example.m3u");

**Comment by sunsgs** [comment]
basically the same with webchimera js is working fine with
player.play("http://siptv.eu/lists/example.m3u");

**Comment by jaruba** [comment]
@sunsgs We've ran accross this particular issue in the past, m3u playlists do not support cross-domain links to other playlists, and that's exactly what your playlist does.

The only solution for you is to read the m3u file in node.js and add each item in it to the player playlist programatically. This cannot be a player issue, nor is it a WebChimera.js issue, we've debugged this before, it's a libVLC issue.

**Comment by RSATom** [comment]
@jaruba, does `wcjs-player` parse `.m3u` files itself? Or does it pass it to wcjs as-is?

I'm thinking why

> basically the same with webchimera js is working fine with player.play("http://siptv.eu/lists/example.m3u");

**Comment by jaruba** [comment]
@RSATom

He is wrong, I don't know why he said that, but it's impossible. `wcjs-player` just pushes the exact link to `WebChimera.js` as-is without doing anything to it, then asks `wcjs` to play it. (like any other MRL for that matter)

I checked what it does with that m3u three times to make sure I'm not wrong just because he wrote that.

**Comment by RSATom** [comment]
@jaruba, thank you for checking it.
