### ISSUE TITLE
Remove minimum constrain on setting volume?

### ISSUE THREAD

**Issue by Zzzen** [jaruba/wcjs-player#61]
```
wjs.prototype.volume = function(newVolume) {
    if (typeof newVolume !== 'undefined' && !isNaN(newVolume) && newVolume >= 0 && newVolume <= 5) {
        // ...
        
    } else if (newVolume && !isNaN(newVolume) && newVolume > 5 && newVolume <= 200) {
        // ...
    } else return this.vlc.volume;
    return this;
}
```
Why should `newVolume` be greater than 5?

**Comment by jaruba** [comment]
Because in `wcjs-player`, I make no difference between the `mute` volume state and `volume == 0`. (this is not what libVLC does though, it's just what I do)

If you look at `.mute`, you'll see that it doesn't use the `mute` state at all (which is something that is available in the `webchimera.js` API)

https://github.com/jaruba/wcjs-player/blob/master/index.js#L801

Did you have any issues with this logic?

**Comment by Zzzen** [comment]
Wouldn't `newVolume > 0` be more intuitive than `newVolume > 5`?

**Comment by jaruba** [comment]
I think the `> 5` is for more flexibility when you move the volume bar, so you don't need to get it to exactly `0` in order to mute sound, but rather just get it very close to the minimum when dragging.

I think any volume of `<= 5` is unhearable anyway. If you think this is unnecessary or that the result is the same with `0` too, you can make a PR for it.

**Comment by Zzzen** [comment]
$(".wcp-surface").addEventListener("wheel", event => {
            const newVal = this.player.volume() + 5 * (event.deltaY > 0 ? -1 : 1);
            this.player.volume(newVal);
        });

When the volume reaches 0, scrolling up has no effect. It took me a long time to debug it.

**Comment by jaruba** [comment]
Wow, I'm not sure if I'm more sorry for putting you through all that or proud of you for finding an ancient bug that was probably in there since I first made `wcjs-player`. :))

**Comment by Zzzen** [comment]
haha
